export const manufacturers = [
  "Honda",
  "Agrale",
  "Bmw",
  "Suzuki",
  "Lifan",
  "Mahindra",
  "Shineray",
  "Kasinski",
  "Yamaha",
  "Garinni",
  "Sundown",
  "Kawasaki",
  "Polaris",
  "Adly",
  "Amazonas",
  "Aprilia",
  "Atala",
  "Bajaj",
  "Benelli",
  "Beta",
  "Bimota",
  "Brandy",
  "Brava",
  "Brp",
  "Buell",
  "Bueno",
  "Cagiva",
  "Mobilete",
  "Daelim",
  "Dafra",
  "Dayang",
  "Dayun",
  "Derbi",
  "Ducati",
  "Emme",
  "Fym",
  "Gas Gas",
  "Green",
  "Haobao",
  "Harley-Davidson",
  "Hartford",
  "Hero",
  "Husaberg",
  "Husqvarna",
  "Iros",
  "Jiapeng Volcano",
  "Johnnypag",
  "Jonny",
  "Kahena",
  "Kimco",
  "Laquila",
  "Landum",
  "Lavrale",
  "Lerivo",
  "Lon-V",
  "Triciclo",
  "Malaguti",
  "Miza",
  "Moto Guzzi",
  "Mrx",
  "Mv Augusta",
  "Mvk",
  "Orca",
  "Pegassi",
  "Piaggio",
  "Regal Raptor",
  "Sanyang",
  "Siamoto",
  "Targos",
  "Traxx",
  "Vento",
  "Wuyang",
  "Garrr",
  "X Motos",
  "Tricker",
  "Lambreta",
  "Outros",
  "Scooter",
  "Zongshen",
  "Birelli",
  "Walk Machine",
  "Fbm",
  "Ariel",
  "Ducar",
  "Ditally",
  "Marva",
  "Wolver",
  "Ktm",
  "Leopard",
  "Jawa",
  "Bull",
  "Can-Am",
  "Acellera",
  "Victory",
  "Indian",
  "Bravax",
  "Garelli"
];


export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  }
];

export const footerLinks = [
  {
    title: "Sobre",
    links: [
      { title: "Em destaque", url: "/" },
      { title: "Parcerias", url: "/" },
    ],
  },
  {
    title: "Redes Sociais",
    links: [
      { title: "Instagram", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
  {
    title: "Conheça o criador",
    links: [
      { title: "GitHub", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
